[job]
retention = 8
jobname   = NAS11day

[email]
email_from = ced@mydomain.com
rcpt_to    = fabrizio.vettore@maindomain.com
# Per più destinatari usare la virgola:
# rcpt_to = uno@example.com, due@example.com
